---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr
  labels:
    type: radarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.radarr
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: radarr
  storageClassName: ""
  volumeName: radarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr
  labels:
    type: sonarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.sonarr
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: sonarr
  storageClassName: ""
  volumeName: sonarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr
  labels:
    type: overseerr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.overseerr
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: overseerr
  storageClassName: ""
  volumeName: overseerr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd
  labels:
    type: sabnzbd
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.sabnzbd
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: sabnzbd
  storageClassName: ""
  volumeName: sabnzbd
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr
  labels:
    type: prowlarr
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.prowlarr
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: prowlarr
  storageClassName: ""
  volumeName: prowlarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbget
  labels:
    type: nzbget
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.nzbget
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: nzbget
  storageClassName: ""
  volumeName: nzbget
---