apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex
      - name: movies
        persistentVolumeClaim:
          claimName: media-movies
      - name: tv
        persistentVolumeClaim:
          claimName: media-tv
      - name: transcode
        type: emptyDir
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        resources:
          limits:
            gpu.intel.com/i915: 1
        imagePullPolicy: Always
        volumeMounts:
        - name: plex-data
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: movies
          mountPath: /movies
        - name: tv
          mountPath: /tv
        env:
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: 'true'
        - name: PLEX_UID
          value: '1027'
        - name: PLEX_GID
          value: '65536'
        - name: TZ
          value: 'America/Denver'
        - name: ADVERTISE_IP
          value: 'http://10.0.1.100:32400'
        ports:
        - name: plex1
          containerPort: 32400
      nodeName: hermes 
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
    - protocol: TCP
      name: plexweb
      port: 32400
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 10.0.1.100