---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: security-authentik-pgsql
  labels:
    type: authentik-pgsql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.authentik
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-authentik-pgsql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: authentik-pgsql
  storageClassName: ""
  volumeName: authentik-pgsql
---
