---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sec-auth-pgsql
  labels:
    type: auth-pgsql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
     targetPortal: 10.0.0.11:3260
     iqn: iqn.2000-01.com.synology:crypteia.auth
     lun: 1
     fsType: 'ext4'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sec-auth-pgsql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: auth-pgsql
  storageClassName: ""
  volumeName: auth-pgsql
---