---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: webtop
  namespace: management
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: rook-ceph-cluster
  #     namespace: rook-ceph
  #   - name: volsync
  #     namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/webtop
              tag: ubuntu-xfce
            env:
              PUID: 1000
              PGID: 1000
              TZ: America/Denver
              TITLE: Desktop
              WEBTOP_PORT: &port 3000
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: false
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 6Gi
        # pod:
        #   securityContext:
        #     runAsUser: 568
        #     runAsGroup: 568
        #     runAsNonRoot: true
        #     fsGroup: 568
        #     fsGroupChangePolicy: OnRootMismatch
        #     supplementalGroups: [10000]
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: &host "{{ .Release.Name }}.spenceops.com"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: false
        #existingClaim: webtop
        #globalMounts:
        #  - path: /config
      tmp:
        type: emptyDir