apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-dev
  template:
    metadata:
      labels:
        app: plex-dev
    spec:
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-dev-config
      - name: media-plex-dev
        persistentVolumeClaim:
          claimName: media-plex-dev
      - name: transcode
        type: emptyDir
      containers:
      - name: plex-dev
        image: plexinc/pms-docker:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: plex-data
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: media-plex-dev
          mountPath: /plex-dev
        env:
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: 'true'
        - name: PLEX_UID
          value: '1027'
        - name: PLEX_GID
          value: '65536'
        - name: TZ
          value: 'America/Denver'
        - name: ADVERTISE_IP
          value: 'http://10.0.1.101:32400'
        ports:
        - name: plex1
          containerPort: 32400
      nodeName: hermes 
---
apiVersion: v1
kind: Service
metadata:
  name: plex-dev
spec:
  ports:
    - protocol: TCP
      name: plex
      port: 32400
  selector:
    app: plex-dev
  type: LoadBalancer
  loadBalancerIP: 10.0.1.101